project:
  type: website
  output-dir: docs

website:
  title: "Modelling Binary Outcomes"
  navbar:
    left:
      - href: index.qmd
        text: Model
      - uncertainty.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



