project:
  type: website
  output-dir: docs
  render:
    - index.qmd          # only this page
    # - pages/*.qmd      # (example) allow a folder of pages later

website:
  title: "Modelling Binary Outcomes"
  navbar:
    left:
      - href: index.qmd
        text: Welcome

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



